- job:
    name: cl-openstack-client-run-tests
    description: |
      Run tests for cl-openstack-client project.
    run: playbooks/run-tests/run.yaml

- project:
    check:
      jobs:
        - cl-openstack-client-run-tests
    gate:
      jobs:
        - cl-openstack-client-run-tests
